"""add owner field

Revision ID: 71f620d4811e
Revises: fe8483c4ccb7
Create Date: 2026-08-03 16:48:41.146352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71f620d4811e'
down_revision: Union[str, Sequence[str], None] = 'fe8483c4ccb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_record_owner'), 'record', ['owner'], unique=False)
    op.execute("Update record SET owner = 'system'")
    # ### end Alembic commands ###


def downgrade() -> None:
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_owner'), table_name='record')
    op.drop_column('record', 'owner')
    # ### end Alembic commands ###
