"""added deleted_at column

Revision ID: fe8483c4ccb7
Revises: c49e947f2aaa
Create Date: 2026-08-03 15:41:25.658502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe8483c4ccb7'
down_revision: Union[str, Sequence[str], None] = 'c49e947f2aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'deleted_at')
    # ### end Alembic commands ###
